# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\" \n\x0f\x45lectionMessage\x12\r\n\x05nodes\x18\x01 \x03(\x05\"\x12\n\x10\x45lectionResponse\".\n\rLeaderMessage\x12\x0e\n\x06leader\x18\x01 \x01(\x05\x12\r\n\x05nodes\x18\x02 \x03(\x05\"\x10\n\x0eLeaderResponse\"\r\n\x0bTimeRequest\"!\n\x0cTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"%\n\x10TimeSynchRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x13\n\x11TimeSynchResponse2\xd6\x01\n\tTicTacToe\x12\x36\n\rStartElection\x12\x10.ElectionMessage\x1a\x11.ElectionResponse\"\x00\x12\x31\n\x0cReportLeader\x12\x0e.LeaderMessage\x1a\x0f.LeaderResponse\"\x00\x12(\n\x07GetTime\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x12\x34\n\tSynchTime\x12\x11.TimeSynchRequest\x1a\x12.TimeSynchResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTIONMESSAGE._serialized_start=19
  _ELECTIONMESSAGE._serialized_end=51
  _ELECTIONRESPONSE._serialized_start=53
  _ELECTIONRESPONSE._serialized_end=71
  _LEADERMESSAGE._serialized_start=73
  _LEADERMESSAGE._serialized_end=119
  _LEADERRESPONSE._serialized_start=121
  _LEADERRESPONSE._serialized_end=137
  _TIMEREQUEST._serialized_start=139
  _TIMEREQUEST._serialized_end=152
  _TIMERESPONSE._serialized_start=154
  _TIMERESPONSE._serialized_end=187
  _TIMESYNCHREQUEST._serialized_start=189
  _TIMESYNCHREQUEST._serialized_end=226
  _TIMESYNCHRESPONSE._serialized_start=228
  _TIMESYNCHRESPONSE._serialized_end=247
  _TICTACTOE._serialized_start=250
  _TICTACTOE._serialized_end=464
# @@protoc_insertion_point(module_scope)
